# .github/workflows/release.yml
name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      flutter_version:
        description: "Flutter version to use, empty for latest"
        required: false
        default: ""
      platforms:
        description: "Platforms to build for"
        required: true
        type: choice
        options:
          - "android"
          - "all"
        default: "android"
  push:
    tags:
      - "v[0-9]+.*"

env:
  FLUTTER_VERSION: ${{ github.event.inputs.flutter_version }}

jobs:
  build-android:
    runs-on: ubuntu-latest
    if: contains(github.event.inputs.platforms, 'android') || contains(github.event.inputs.platforms, 'all') || startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Figure out DIR
        run: |
          ref="${{ github.ref_name }}"
          echo "ref: $ref"
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            ref=${ref#v}
          fi
          echo "DIR=${ref}" >> "$GITHUB_ENV"

      - name: Use the DIR
        run: |
          echo $DIR
          echo ${{ env.DIR }}

      - name: Decode keystore file
        env:
          FILESYNC_KEYSTORE_FILE_BASE64: ${{ secrets.FILESYNC_KEYSTORE_FILE_BASE64 }}
        run: echo $FILESYNC_KEYSTORE_FILE_BASE64 | base64 --decode > android/app/file_sync.jks

      - name: temp debug
        env:
          FILESYNC_KEY_PASSWORD: ${{ secrets.FILESYNC_KEY_PASSWORD }}
        run: |
          md5sum android/app/file_sync.jks

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - run: flutter --version

      - name: Flutter build apk
        env:
          FILESYNC_KEY_PASSWORD: ${{ secrets.FILESYNC_KEY_PASSWORD }}
        run: |
          version_str=$(cat pubspec.yaml | grep 'version: ' | sed 's/version: //')
          version_number=$(echo $version_str | cut -d'+' -f1)
          build_number=$(echo $version_str | cut -d'+' -f2)
          flutter build apk --release --dart-define="APP_VERSION=$version_number" --dart-define="APP_BUILD_NUMBER=$build_number"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: file_sync.apk
          path: build/app/outputs/apk/release/app-release.apk

      - name: Upload apk to release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          repo_token: ${{ secrets.FILESYNC_GITHUB_TOKEN }}
          file: build/app/outputs/apk/release/app-release.apk
          asset_name: file_sync.apk
          tag: ${{ github.ref }}
          overwrite: true
      
